# adapted from https://github.com/tock/elf2tab/blob/master/.github/workflows/cargo.yml

name: Cargo

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
